[book]
title = "Doge Connect"
description = "Doge Connect - Payment Protocol."
authors = ["qlpqlp", "tjstebbing"]
language = "en"
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/dogeorg/connect/"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/dogeorg/connect/edit/main/{path}"
cname = "connect.dogecoin.org"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
